### ISSUE TITLE
Migrate from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by divyeshio** [dzaliznyak/Meta.Lib#6]
### Why switch?

Over the years System.Text.Json has come a long way and improved a lot, even beyond Newtonsoft.Json. Some major reasons of switching to System.Text.Json include:

-   A major increase in performance when serializing and deserializing Data
-   Cutting down on a 3rd party library and replacing it with an official one
-   More robust in terms of security and reliability
-   Performance that is tailored towards the targeted framework

### Additions with switching

A lot of code will need to be migrated over to System.Text.Json, many things that used to be specified with attributes when using Newtonsoft.Json will now need to be added as a setting in the serializer/deserializer.

### Problems with switching

No problems should arise if everything is tested correctly after the code was migrated over.

**Comment by dzaliznyak** [comment]
Done in v. 2.0
